spring:
  profiles:
    active: dev
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mypiano?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    hikari:
      maximum-pool-size: 30      # 최대 커넥션 수
      minimum-idle: 10           # 최소 유지 커넥션 수
      idle-timeout: 60000        # idle 커넥션 유지 시간 (ms)
      max-lifetime: 1800000      # 커넥션 최대 수명 (ms)
      connection-timeout: 30000  # 커넥션 획득 타임아웃 (ms)
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.omegafrog.My.piano.app.web.event
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        generate_statistics: false
        use_sql_comments: false
    hibernate:
      ddl-auto: update
  cloud:
    aws:
      region:
        static: ap-northeast-2
      bucket:
        name: mypianobucket
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/api/v1/oauth2/google/callback
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  redis:
    user:
      host: 127.0.0.1
      port: 6379
    cache:
      host: 127.0.0.1
      port: 6380
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  file:
    name: log.txt
#   level:
#     org.springframework.web: DEBUG
#     org.springframework.http.converter.json: DEBUG
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type.descriptor.sql: TRACE

elasticsearch:
  host: localhost
  port: 9200

async:
  pool:
    core: 50
    max: 200
  queue:
    capacity: 20000

security:
  password:
    expire:
      period: 90L
  jwt:
    accessToken:
      period: 6000000
    refreshToken:
      period: 1209600

firebase:
  app:
    admin:
      json: src/main/resources/firebase-admin.json

payment:
  toss:
    api-url: https://api.tosspayments.com/v1/payments

server:
  tomcat:
    threads:
      max: 200
local:
  storage:
    base-path: ./static